//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineTwitterDataCollection_WinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coordinate
    {
        public int Id { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public Nullable<int> TwitterGeo_Id { get; set; }
        public Nullable<int> TwitterBoundingBox_Id { get; set; }
    
        public virtual TwitterBoundingBox TwitterBoundingBox { get; set; }
        public virtual TwitterGeo TwitterGeo { get; set; }
    }
}
