//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineTwitterDataCollection_WinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaSize
    {
        public int Id { get; set; }
        public int Size { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public int Resize { get; set; }
        public Nullable<int> TwitterMediaEntity_TwitterEntityId { get; set; }
    
        public virtual TwitterEntity TwitterEntity { get; set; }
    }
}
