//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineTwitterDataCollection_WinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TwitterUser
    {
        public TwitterUser()
        {
            this.TwitterStatus = new HashSet<TwitterStatu>();
        }
    
        public decimal Id { get; set; }
        public string StringId { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }
        public bool IsDefaultProfile { get; set; }
        public bool IsDefaultProfileImage { get; set; }
        public bool IsTranslator { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string TimeZone { get; set; }
        public Nullable<long> NumberOfFollowers { get; set; }
        public long NumberOfStatuses { get; set; }
        public long NumberOfFriends { get; set; }
        public bool IsContributorsEnabled { get; set; }
        public string Language { get; set; }
        public string ScreenName { get; set; }
        public long NumberOfFavorites { get; set; }
        public bool IsProtected { get; set; }
        public Nullable<bool> IsGeoEnabled { get; set; }
        public string CountriesWithheld { get; set; }
        public string WithheldScope { get; set; }
        public Nullable<double> TimeZoneOffset { get; set; }
        public string Website { get; set; }
        public int ListedCount { get; set; }
        public Nullable<bool> FollowRequestSent { get; set; }
        public Nullable<bool> Verified { get; set; }
        public string ProfileBackgroundColorString { get; set; }
        public Nullable<bool> IsProfileBackgroundTiled { get; set; }
        public string ProfileLinkColorString { get; set; }
        public string ProfileBackgroundImageLocation { get; set; }
        public bool UseProfileBackgroundImage { get; set; }
        public string ProfileBannerLocation { get; set; }
        public string ProfileTextColorString { get; set; }
        public string ProfileImageLocation { get; set; }
        public string ProfileImageSecureLocation { get; set; }
        public string ProfileSidebarBorderColorString { get; set; }
        public string ProfileSidebarFillColorString { get; set; }
    
        public virtual ICollection<TwitterStatu> TwitterStatus { get; set; }
    }
}
