//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineTwitterDataCollection_WinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TwitterPlace
    {
        public TwitterPlace()
        {
            this.TwitterStatus = new HashSet<TwitterStatu>();
        }
    
        public string Id { get; set; }
        public string CountryCode { get; set; }
        public string PlaceType { get; set; }
        public string DataAddress { get; set; }
        public string Country { get; set; }
        public string StreetAddress { get; set; }
        public string PostalCode { get; set; }
        public string Phone { get; set; }
        public string Locality { get; set; }
        public string Region { get; set; }
        public string Iso3CountryCode { get; set; }
        public string FullName { get; set; }
        public string Name { get; set; }
        public string AppIds { get; set; }
        public Nullable<int> BoundingBox_Id { get; set; }
    
        public virtual TwitterBoundingBox TwitterBoundingBox { get; set; }
        public virtual ICollection<TwitterStatu> TwitterStatus { get; set; }
    }
}
