//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineTwitterDataCollection_WinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TwitterEntity
    {
        public TwitterEntity()
        {
            this.MediaSizes = new HashSet<MediaSize>();
        }
    
        public int TwitterEntityId { get; set; }
        public int StartIndex { get; set; }
        public int EndIndex { get; set; }
        public string Text { get; set; }
        public string ScreenName { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> UserId { get; set; }
        public string Url { get; set; }
        public string DisplayUrl { get; set; }
        public string ExpandedUrl { get; set; }
        public Nullable<int> MediaType { get; set; }
        public Nullable<decimal> Id { get; set; }
        public string IdString { get; set; }
        public string MediaUrl { get; set; }
        public string MediaUrlSecure { get; set; }
        public string Discriminator { get; set; }
        public Nullable<decimal> TwitterStatus_Id { get; set; }
    
        public virtual ICollection<MediaSize> MediaSizes { get; set; }
        public virtual TwitterStatu TwitterStatu { get; set; }
    }
}
